trainer:
  max_steps: &max_steps !combination
    name: ds
    pairs:
      imnet: 200000
      cif10: 10000
      oxpet: 10000
      sfcar: 10000
  val_check_interval: &val_check_interval !combination
    name: ds
    pairs:
      imnet: 1000
      cif10: 100
      oxpet: 100
      sfcar: 100
  check_val_every_n_epoch: null
  log_every_n_steps: *val_check_interval
  max_epochs: -1

callbacks:
  - type: pl_callback
    name: LearningRateMonitor
    params:
      logging_interval: step
  - type: OneShotMagnitudePruning
    params:
      module_include: &module_include !combination
        name: model
        pairs:
          vitbs: ["nn.modules.Linear"]
          res50: ["nn.modules.Conv2d"]
          effb3: ["nn.modules.Conv2d"]
      module_ignore: &module_ignore !combination
        name: model
        pairs:
          vitbs: ["head"]
          res50: ["conv1"]
          effb3: ["conv_stem"]
      prune_target: &target 0.0
      prune_timing: 0.0
      monitor_prefix: progress
      layer_norm: true
  - type: SparsityMonitor
    params:
      name: &sparsity_metric progress/sparsity
      module_include: *module_include
      module_ignore: *module_ignore
  - type: PatientCheckpoint
    params:
      lookout_param: *sparsity_metric
      comparison: [__ge__, *target]
      save_top_k: 1
      monitor: val/top1
      mode: max
      filename: "{step:08d}"

task:
  type: ImageClassification

  model:
    type: timm_model_autoclasses
    params:
      model_name: !combination
        name: model
        pairs:
          vitbs: vit_base_patch16_224
          res50: resnet50
          effb3: efficientnet_b3
      pretrained: !combination
        name: ds
        pairs:
          imnet: false
          cif10: true
          oxpet: true
          sfcar: true
      seed: !combination
        name: seed
        pairs:
          s1: 42
          s2: 1729
          s3: 24601
    model_input: [3, &dim 224, *dim]

  loss:
    type: torch_loss
    params:
      name: CrossEntropyLoss

  metrics:
    - {type: TopKAccuracy, name: top1, params: {k: 1}}
    - {type: TopKAccuracy, name: top5, params: {k: 5}}

  optimizer:
    type: torch_optimizer
    params:
      optimizer_name: AdamW
      lr: 1.0e-4
  
  scheduler:
    type: CyclicStepLR
    params:
      warmup_lr_ratio: 0.01
      target_lr_ratio: 0.01
      total_steps: *max_steps
      warmup_ratio: 0.1
      cycles: 1
    config_params:
      interval: step
      frequency: 1
      name: progress/lr
  
  cutmix:
    mixup_alpha: 0.2
    cutmix_alpha: 0.0
  cutmix_off_timing: 0.5

dataset:
  type: !combination
    name: ds
    pairs:
      imnet: ImageFolderImclassV1
      cif10: TorchvisionImclassV1
      oxpet: TorchvisionImclassV1
      sfcar: TorchvisionImclassV1
  params: !combination
    name: ds
    pairs:
      imnet:
        train_root: data/imagenet/train
        val_root: data/imagenet/val
      cif10:
        name: CIFAR10
        root: data/CIFAR10
        reformat_tts: 0.1
      oxpet:
        name: OxfordIIITPet
        root: data/OxfordIIITPet
        reformat_tts: 0.1
      sfcar:
        name: StanfordCars
        root: data/StanfordCars
        reformat_tts: 0.1

  transforms:
    train: &transform
      - {type: torchvision_transform, name: Resize, params: {size: [*dim, *dim]}}
      - {type: torchvision_transform, name: ToTensor, params: {}}
      - {type: torchvision_transform, name: Normalize, params: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}}
    validation: *transform
        
  dataloader:
    batch_size: 128
    shuffle_seed: !combination
      name: seed
      pairs:
        s1: 42
        s2: 1729
        s3: 24601